<link rel="stylesheet" href="css/style.css">
<link href="bootstrap/css/bootstrap.css" rel="stylesheet">     
 <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Over-Root</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><a href="main.php">Home</a></li>
            <li><a href="#main.html">Menu</a></li>
            <li><a href="#contact">Contact</a></li>
            <li><a href="lista_usuarios.php">Listado de usuarios</a></li>
            <li id="logout"><a href="cerrarsesion.php">Cerrar sesion</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
